Repository boostcampwm-2024/web04-RealTicket, pull requests merged in 2024-11, with the labels that each got.

#24 백엔드 개발 세팅
  .gitignore
  back/.eslintrc.js
  back/.prettierrc
  back/README.md
  back/nest-cli.json
  back/package-lock.json
  back/package.json
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/main.ts
  back/test/app.e2e-spec.ts
  back/test/jest-e2e.json
  back/tsconfig.build.json
  back/tsconfig.json
Labels: 🛠️백엔드, 💩chore

#25 프론트 개발 세팅
  .gitignore
  .gitmessage.txt
  .husky/pre-commit
  .nvmrc
  front/.prettierIgnore
  front/.prettierrc
  front/eslint.config.js
  front/index.html
  front/package-lock.json
  front/package.json
  front/public/vite.svg
  front/src/App.css
  front/src/App.tsx
  front/src/assets/react.svg
  front/src/index.css
  front/src/main.tsx
  front/src/vite-env.d.ts
  front/tsconfig.app.json
  front/tsconfig.json
  front/tsconfig.node.json
  front/vite.config.ts
  package-lock.json
  package.json
  scripts/branch-create.sh
  scripts/makeLinkedBranch.js
Labels: 🔧프론트

#27 📝 docs: 커밋 탬플릿 추가
  .commit-template.txt
Labels: 📃문서

#28 userlayer 추가
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/dto/userCreate.dto.ts
  back/src/entity/user.entity.ts
  back/src/user/user.controller.spec.ts
  back/src/user/user.controller.ts
  back/src/user/user.repository.ts
  back/src/user/user.service.spec.ts
  back/src/user/user.service.ts
Labels: 🛠️백엔드, ✨feature

#31 프론트 개발 설정
  .gitmessage.txt
  front/.prettierrc
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/public/vite.svg
  front/src/App.css
  front/src/App.tsx
  front/src/assets/fonts/Pretendard-ExtraBold.subset.woff2
  front/src/assets/fonts/Pretendard-ExtraLight.subset.woff2
  front/src/assets/fonts/Pretendard-Medium.subset.woff2
  front/src/assets/fonts/Pretendard-Regular.subset.woff2
  front/src/assets/react.svg
  front/src/index.css
  front/src/layout/Layout.tsx
  front/src/pages/DetailPage.tsx
  front/src/pages/MainPage.tsx
  front/src/routes/index.tsx
  front/style/colors.ts
  front/style/fontSize.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/vite.config.ts
Labels: 🔧프론트, ✨feature

#47 도메인 별 디렉토리 생성
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/place/place.module.ts
  back/src/place/place.service.spec.ts
  back/src/place/place.service.ts
  back/src/program/entities/program.entity.ts
  back/src/program/program.controller.spec.ts
  back/src/program/program.controller.ts
  back/src/program/program.module.ts
  back/src/program/program.service.spec.ts
  back/src/program/program.service.ts
  back/src/reservation/reservation.controller.spec.ts
  back/src/reservation/reservation.controller.ts
  back/src/reservation/reservation.module.ts
  back/src/reservation/reservation.service.spec.ts
  back/src/reservation/reservation.service.ts
  back/src/util/util.controller.spec.ts
  back/src/util/util.controller.ts
  back/src/util/util.module.ts
  back/src/util/util.service.spec.ts
  back/src/util/util.service.ts
Labels: 🛠️백엔드, 🏛️infra

#49 app.module 불필요 의존성 제거
  back/src/app.module.ts
Labels: 🛠️백엔드, 🚨hotfix

#30 유저 인증 및 인가 Guard 구현, 유저 회원가입, 유저 로그인 & 로그아웃
  back/.eslintignore
  back/package-lock.json
  back/package.json
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/auth/auth.module.ts
  back/src/auth/const/userStatus.const.ts
  back/src/auth/guard/auth.guard.ts
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/config/redisConfig.ts
  back/src/config/typeOrmConfig.ts
  back/src/decorator/not-in.ts
  back/src/dto/userCreate.dto.ts
  back/src/entity/user.entity.ts
  back/src/main.ts
  back/src/user/controller/user.controller.spec.ts
  back/src/user/controller/user.controller.ts
  back/src/user/dto/userCreate.dto.ts
  back/src/user/dto/userLogin.dto.ts
  back/src/user/entity/user.entity.ts
  back/src/user/repository/user.repository.ts
  back/src/user/service/user.service.spec.ts
  back/src/user/service/user.service.ts
  back/src/user/user.controller.ts
  back/src/user/user.module.ts
  back/src/user/user.service.ts
  back/tsconfig.json
  package-lock.json
  package.json
Labels: 🛠️백엔드, ✨feature

#54 목 API 구현
  back/src/app.module.ts
  back/src/mock/booking/booking.controller.ts
  back/src/mock/booking/booking.module.ts
  back/src/mock/booking/booking.service.ts
  back/src/mock/event/event.controller.ts
  back/src/mock/event/event.module.ts
  back/src/mock/event/event.service.ts
  back/src/mock/mock.module.ts
  back/src/mock/place/place.controller.ts
  back/src/mock/place/place.module.ts
  back/src/mock/place/place.service.ts
  back/src/mock/program/program.controller.ts
  back/src/mock/program/program.module.ts
  back/src/mock/program/program.service.ts
  back/src/mock/reservation/reservation.controller.spec.ts
  back/src/mock/reservation/reservation.controller.ts
  back/src/mock/reservation/reservation.module.ts
  back/src/mock/reservation/reservation.service.spec.ts
  back/src/mock/reservation/reservation.service.ts
Labels: 🛠️백엔드, ✨feature

#55 Feat/#40 event data
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/config/redisConfig.ts
  back/src/event/controller/event.controller.spec.ts
  back/src/event/controller/event.controller.ts
  back/src/event/dto/eventIdDto.ts
  back/src/event/dto/eventSpecificDto.ts
  back/src/event/dto/placeSpecificEventDto.ts
  back/src/event/event.controller.ts
  back/src/event/event.module.ts
  back/src/event/event.service.ts
  back/src/event/repository/event.reposiotry.ts
  back/src/event/service/event.service.spec.ts
  back/src/event/service/event.service.ts
  back/src/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature

#56 컴포넌트 작성 - Input, Button, useForm
  front/.prettierrc
  front/package-lock.json
  front/package.json
  front/src/components/common/Button.tsx
  front/src/components/common/Field.tsx
  front/src/components/common/Input.tsx
  front/src/components/common/Slot.tsx
  front/src/contexts/fieldContext.tsx
  front/src/hooks/useForm.tsx
  front/style/colors.ts
  front/style/fontSize.ts
Labels: 🔧프론트, ✨feature

#62 백엔드 Mock 모드 실행 지원
  back/src/app.module.ts
Labels: 🛠️백엔드, ✨feature

#71 util 모듈 제거
  back/src/app.module.ts
  back/src/domains/util/controller/util.controller.spec.ts
  back/src/domains/util/controller/util.controller.ts
  back/src/domains/util/service/util.service.spec.ts
  back/src/domains/util/service/util.service.ts
  back/src/domains/util/util.module.ts
Labels: 🛠️백엔드, 🏛️infra

#75 🐛 fix: npm 의존성 위치 변경
  back/package-lock.json
  back/package.json
  back/src/main.ts
  package-lock.json
  package.json
Labels: 🛠️백엔드, 🚨hotfix

#76 Feat/#23 user inject
  back/src/app.module.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/user/repository/user.repository.ts
  back/src/domains/user/service/user.service.ts
  back/src/util/user-injection/user.decorator.middleware.ts
  back/src/util/user-injection/user.decorator.module.ts
  back/src/util/user-injection/user.decorator.service.ts
  back/src/util/user-injection/user.decorator.ts
  back/src/util/user-injection/userParamDto.ts
Labels: 🛠️백엔드, ✨feature

#77 💩 chore: 유저 객체 주입 클래스 변경
  back/src/util/user-injection/user.decorator.service.ts
Labels: 🛠️백엔드, 💩chore

#80 Feat/#79 request body transformer
  back/package-lock.json
  back/package.json
  back/src/main.ts
  back/src/util/convention-transformer/transformer.interceptor.ts
Labels: 🛠️백엔드, 💩chore

#84 'camelcase-keys' 패키지 임포트 에러
  back/package-lock.json
  back/package.json
Labels: 🛠️백엔드, 🚨hotfix

#85 예매 매수 설정 API
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/const/bookingAmount.const.ts
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/dto/bookingAmountReqDto.ts
  back/src/domains/booking/dto/bookingAmountResDto.ts
  back/src/domains/booking/service/in-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#88 컴포넌트 작성 - Navbar, icon , Popover
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/assets/icons/check.svg
  front/src/assets/icons/down-arrow.svg
  front/src/assets/icons/fie-x.svg
  front/src/assets/icons/home.svg
  front/src/assets/icons/index.ts
  front/src/assets/icons/loading.svg
  front/src/assets/icons/log-out.svg
  front/src/assets/icons/tickets.svg
  front/src/assets/icons/trash.svg
  front/src/assets/icons/up-arrow.svg
  front/src/assets/icons/user.svg
  front/src/components/common/Button.tsx
  front/src/components/common/Field.tsx
  front/src/components/common/Icon.tsx
  front/src/components/common/Input.tsx
  front/src/components/common/Navbar.tsx
  front/src/components/common/Popover.tsx
  front/src/components/common/Separator.tsx
  front/src/contexts/AuthContext.tsx
  front/src/contexts/fieldContext.tsx
  front/src/hooks/useAuthContext.tsx
  front/src/hooks/useAuthReducer.tsx
  front/src/hooks/useFieldContext.tsx
  front/src/layout/Layout.tsx
  front/src/providers/AuthProvider.tsx
  front/src/utils/getDate.ts
  front/src/vite-env.d.ts
  front/style/colors.ts
  front/tailwind.config.js
  front/tsconfig.app.json
  front/vite.config.ts
Labels: 🔧프론트, ✨feature

#90 Feat/#78 swagger user controller
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/dto/userCreate.dto.ts
  back/src/domains/user/dto/userLogin.dto.ts
  back/src/domains/user/dto/userLoginIdCheck.dto.ts
  back/src/domains/user/repository/user.repository.ts
  back/src/domains/user/service/user.service.ts
  back/src/util/logger/winstonlogger.config.ts
  back/src/util/logger/winstonlogger.middleware.ts
Labels: 🛠️백엔드, 💩chore

#91 로그인 회원가입 페이지
  front/index.html
  front/package.json
  front/src/hooks/useForm.tsx
  front/src/layout/Layout.tsx
  front/src/pages/SignInPage.tsx
  front/src/pages/SignUpPage.tsx
  front/src/routes/index.tsx
Labels: 🔧프론트, ✨feature

#96 프로그램 선택 페이지
  front/src/App.tsx
  front/src/components/common/Navbar.tsx
  front/src/components/common/Skeleton.tsx
  front/src/layout/Layout.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/ProgramsPage.tsx
  front/src/routes/index.tsx
Labels: 🔧프론트, ✨feature

#102 프로그램 상세 페이지
  front/src/components/common/Input.tsx
  front/src/components/common/Navbar.tsx
  front/src/components/common/Radio.tsx
  front/src/components/common/Separator.tsx
  front/src/pages/ProgramDetailPage.tsx
  front/src/pages/ProgramsPage.tsx
  front/src/utils/date.ts
  front/src/utils/getDate.ts
  front/src/utils/getPriceWon.ts
Labels: 🔧프론트, ✨feature

#104 Feat/#41 seat data
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/place/controller/place.controller.ts
  back/src/domains/place/dto/layout.dto.ts
  back/src/domains/place/dto/seatInfo.dto.ts
  back/src/domains/place/dto/section.dto.ts
  back/src/domains/place/example/response/getSeatResponseExample.ts
  back/src/domains/place/place.module.ts
  back/src/domains/place/repository/section.repository.ts
  back/src/domains/place/service/place.service.ts
Labels: 🛠️백엔드, ✨feature

#105 예매 대기 페이지
  front/public/images/stageSimple.svg
  front/src/assets/icons/clock.svg
  front/src/assets/icons/index.ts
  front/src/layout/Layout.tsx
  front/src/pages/ReservationWaitingPage.tsx
  front/src/routes/index.tsx
Labels: 🔧프론트, ✨feature

#107 API별 도메인 재배치
  back/src/mock/event/event.controller.ts
  back/src/mock/event/event.service.ts
  back/src/mock/reservation/reservation.controller.ts
  back/src/mock/reservation/reservation.service.ts
Labels: 🛠️백엔드, 🏛️infra

#114 Feat/#113 add user entity role
  back/src/domains/user/const/userRole.ts
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/entity/user.entity.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature

#116 예매 진행 페이지
  front/eslint.config.js
  front/package-lock.json
  front/package.json
  front/src/components/common/Input.tsx
  front/src/components/common/Separator.tsx
  front/src/pages/AdminPage.tsx
  front/src/pages/NotFoundPage.tsx
  front/src/pages/ProgramDetailPage.tsx
  front/src/pages/ReservationPage/ReservationResult.tsx
  front/src/pages/ReservationPage/SeatCountAndCaptcha.tsx
  front/src/pages/ReservationPage/SectionAndSeat.tsx
  front/src/pages/ReservationPage/SectionSelectorMap.tsx
  front/src/pages/ReservationPage/index.tsx
  front/src/pages/ReservationWaitingPage.tsx
  front/src/routes/index.tsx
  front/src/utils/svg.ts
  package.json
Labels: ✨feature

#129 회원가입 로그인 api 연결
  front/eslint.config.js
  front/package-lock.json
  front/package.json
  front/public/images/post1.jpg
  front/public/images/post2.jpg
  front/public/images/post3.jpg
  front/src/App.tsx
  front/src/api/axios.ts
  front/src/api/event.ts
  front/src/api/program.ts
  front/src/api/user.ts
  front/src/assets/icons/calendar.svg
  front/src/assets/icons/check-circle.svg
  front/src/assets/icons/index.ts
  front/src/assets/icons/map-pin.svg
  front/src/assets/icons/ticket.svg
  front/src/components/common/Button.tsx
  front/src/components/common/Navbar.tsx
  front/src/components/common/Slot.tsx
  front/src/constants/index.ts
  front/src/contexts/AuthContext.tsx
  front/src/hooks/useAuth.tsx
  front/src/hooks/useAuthReducer.tsx
  front/src/hooks/useForm.tsx
  front/src/layout/Layout.tsx
  front/src/pages/LoadingPage.tsx
  front/src/pages/ProgramDetailPage.tsx
  front/src/pages/ProgramsPage.tsx
  front/src/pages/ReservationPage/ReservationResult.tsx
  front/src/pages/ReservationPage/SectionAndSeat.tsx
  front/src/pages/ReservationPage/index.tsx
  front/src/pages/SignInPage.tsx
  front/src/pages/SignUpPage.tsx
  front/src/providers/AuthProvider.tsx
  front/src/providers/QueryProvider.tsx
  front/src/type/index.ts
  front/src/utils/getPriceWon.ts
  front/src/utils/transform.ts
  front/test/transform.test.ts
  front/vite.config.ts
Labels: 🔧프론트, ✨feature

#130 로그인 로직 리팩토링
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/dto/userCreate.dto.ts
  back/src/domains/user/dto/userLogin.dto.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#141 api 카멜 케이스 변경 적용
  front/src/api/axios.ts
  front/src/api/user.ts
  front/src/constants/index.ts
  front/src/pages/LoginPage.tsx
  front/src/pages/SignUpPage.tsx
  front/src/routes/index.tsx
Labels: 🔧프론트, ✨feature

#149 유저flow api 연결
  front/public/images/poster1.jpg
  front/public/images/poster2.jpg
  front/public/images/poster3.jpg
  front/src/api/event.ts
  front/src/api/place.ts
  front/src/api/program.ts
  front/src/components/common/Navbar.tsx
  front/src/constants/index.ts
  front/src/hooks/useForm.tsx
  front/src/pages/EventDetailPage.tsx
  front/src/pages/LoginPage.tsx
  front/src/pages/ProgramDetailPage.tsx
  front/src/pages/ProgramsPage.tsx
  front/src/pages/ReservationPage/ReservationResult.tsx
  front/src/pages/ReservationPage/SectionAndSeat.tsx
  front/src/pages/ReservationPage/SectionSelectorMap.tsx
  front/src/pages/ReservationPage/index.tsx
  front/src/pages/ReservationWaitingPage.tsx
  front/src/routes/index.tsx
  front/src/type/index.ts
  front/src/utils/date.ts
  front/tailwind.config.js
Labels: 🔧프론트, ✨feature

#164 좌석 확정 API 로직변경
  back/src/auth/guard/session.guard.ts
  back/src/domains/event/repository/event.reposiotry.ts
  back/src/domains/place/repository/section.repository.ts
  back/src/domains/reservation/controller/reservation.controller.ts
  back/src/domains/reservation/dto/reservationCreateDto.ts
  back/src/domains/reservation/dto/reservationDataDto.ts
  back/src/domains/reservation/dto/reservationSeatInfoDto.ts
  back/src/domains/reservation/repository/reservedSeat.repository.ts
  back/src/domains/reservation/reservation.module.ts
  back/src/domains/reservation/service/reservation.service.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ⚙️refactor

#162 Navbar 자동 로그인 및 api 추가
  front/package.json
  front/src/App.tsx
  front/src/api/axios.ts
  front/src/api/reservation.ts
  front/src/api/user.ts
  front/src/components/Navbar/ReservationCard.tsx
  front/src/components/Navbar/index.tsx
  front/src/components/Seats/SeatsContainer.tsx
  front/src/components/loaders/WithLogin.tsx
  front/src/components/loaders/WithoutLogin.tsx
  front/src/constants/index.ts
  front/src/contexts/AuthContext.tsx
  front/src/events/AuthEvent.ts
  front/src/layout/Layout.tsx
  front/src/pages/EventDetailPage.tsx
  front/src/pages/LoginPage.tsx
  front/src/providers/AuthProvider.tsx
  front/src/providers/QueryProvider.tsx
  front/src/routes/index.tsx
  front/src/type/index.ts
  front/src/type/reservation.ts
  front/src/type/user.ts
  front/vite.config.ts
Labels: 🔧프론트, ✨feature

#166 SSE 브로드캐스트 리팩토링
  back/src/domains/booking/const/seatsBroadcastInterval.const.ts
  back/src/domains/booking/const/seatsSseRetryTime.const.ts
  back/src/domains/booking/luaScripts/getSeatsLua.ts
  back/src/domains/booking/service/booking-seats.service.ts
Labels: 🛠️백엔드, ⚙️refactor

#168 대기 큐 구현
  back/package-lock.json
  back/package.json
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/const/inBookingPoolSize.const.ts
  back/src/domains/booking/const/waitingBroadcastInterval.const.ts
  back/src/domains/booking/const/watingThroughputRate.const.ts
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/booking/service/open-booking.service.ts
  back/src/domains/booking/service/waiting-queue.service.ts
Labels: 🛠️백엔드, ✨feature

#169 Feat/#163 folder captcha
  front/package-lock.json
  front/package.json
  front/src/assets/icons/refresh.svg
  front/src/components/Captcha/index.css
  front/src/components/Captcha/index.tsx
  front/src/layout/Layout.tsx
  front/src/pages/AdminPage/index.tsx
  front/src/pages/LoadingPage.tsx
  front/src/pages/LoginPage/index.tsx
  front/src/pages/NotFoundPage.tsx
  front/src/pages/ProgramDetailPage/ProgramInformation.tsx
  front/src/pages/ProgramDetailPage/index.tsx
  front/src/pages/ProgramsPage/ProgramCard.tsx
  front/src/pages/ProgramsPage/index.tsx
  front/src/pages/ReservationPage/SeatCount.tsx
  front/src/pages/ReservationPage/SeatCountAndCaptcha.tsx
  front/src/pages/ReservationPage/index.tsx
  front/src/pages/ReservationWaitingPage/index.tsx
  front/src/pages/SignupPage/index.tsx
  front/src/routes/index.tsx
  front/src/type/react-simple-captcha.d.ts
  front/tsconfig.app.json
Labels: 🔧프론트, ✨feature

#180 좌석 현황 읽기 예외 처리
  back/src/domains/booking/luaScripts/getSeatsLua.ts
  back/src/domains/booking/service/booking-seats.service.ts
Labels: 🛠️백엔드, ✨feature

#182 대기 큐에 대기 중인 인원이 없을 때에도 pop하는 문제
  back/src/domains/booking/service/waiting-queue.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#185 RDB에 Section.seats 저장 타입 일치 문제
  back/src/domains/booking/service/open-booking.service.ts
  back/src/domains/place/entity/section.entity.ts
Labels: 🛠️백엔드, 🚨hotfix

#195 인증 및 인가 리팩토링
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ⚙️refactor

#198 관리자 기능: 좌석 선택 페이지 입장 가능 인원 조정
  back/src/domains/booking/const/inBookingDefaultMaxSize.const.ts
  back/src/domains/booking/const/inBookingPoolSize.const.ts
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/dto/inBookingSizeReq.dto.ts
  back/src/domains/booking/dto/inBookingSizeRes.dto.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/booking/service/open-booking.service.ts
  back/src/domains/booking/service/waiting-queue.service.ts
Labels: 🛠️백엔드, ✨feature

#199 좌석 확정 예매 매수 설정 비교 로직
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/dto/bookReq.dto.ts
  back/src/domains/booking/dto/bookRes.dto.ts
  back/src/domains/booking/dto/bookingAdmissionStatus.dto.ts
  back/src/domains/booking/dto/bookingAmountReq.dto.ts
  back/src/domains/booking/dto/bookingAmountRes.dto.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/event/controller/event.controller.ts
  back/src/domains/event/dto/event.dto.ts
  back/src/domains/event/dto/eventCreation.dto.ts
  back/src/domains/event/dto/eventId.dto.ts
  back/src/domains/event/dto/eventSpecific.dto.ts
  back/src/domains/event/dto/placeSpecificEvent.dto.ts
  back/src/domains/event/service/event.service.ts
  back/src/domains/program/controller/program.controller.ts
  back/src/domains/program/dto/eventSpecificProgram.dto.ts
  back/src/domains/program/dto/placeMainPage.dto.ts
  back/src/domains/program/dto/placeSpecificProgram.dto.ts
  back/src/domains/program/dto/programCreation.dto.ts
  back/src/domains/program/dto/programId.dto.ts
  back/src/domains/program/dto/programMainPage.dto.ts
  back/src/domains/program/dto/programSpecific.dto.ts
  back/src/domains/program/service/program.service.ts
  back/src/domains/reservation/controller/reservation.controller.ts
  back/src/domains/reservation/dto/reservationCreate.dto.ts
  back/src/domains/reservation/dto/reservationId.dto.ts
  back/src/domains/reservation/dto/reservationResult.dto.ts
  back/src/domains/reservation/dto/reservationSeatInfo.dto.ts
  back/src/domains/reservation/dto/reservationSepecific.dto.ts
  back/src/domains/reservation/reservation.module.ts
  back/src/domains/reservation/service/reservation.service.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature, ⚙️refactor

#205 중복 로그인 방지로직
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature

#215 좌석 선택 페이지 기본 최대 인원 수 설정 문제
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#216 예매 오픈 스케줄링 시 기존 이벤트 초기화 문제
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#218 관리자 기능: 좌석 선택 페이지 기본 사이즈 설정
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/service/in-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#220 AuthService 속 함수들 책임 분리
  back/src/auth/service/auth.service.ts
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/service/booking-seats.service.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/booking/service/waiting-queue.service.ts
  back/src/domains/reservation/reservation.module.ts
  back/src/domains/reservation/service/reservation.service.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ⚙️refactor

#229 대기 큐 누수 대응
  back/src/auth/const/userStatus.const.ts
  back/src/auth/guard/session.guard.ts
  back/src/auth/service/auth.service.ts
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/const/enterBooking.const.ts
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/enter-booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#232 대기 큐: 대기자가 없을 때 headOrder null반환 문제
  back/src/domains/booking/service/waiting-queue.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#235 좌석 선택 중 이탈 시 좌석 회수
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/reservation/service/reservation.service.ts
Labels: 🛠️백엔드, ✨feature

#237 레이아웃 및 api 최적화
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/api/axios.ts
  front/src/components/Captcha/index.tsx
  front/src/components/Navbar/index.tsx
  front/src/components/Toast/Toast.tsx
  front/src/components/Toast/ToastContainer.tsx
  front/src/components/common/Popover.tsx
  front/src/components/loaders/WithLogin.tsx
  front/src/components/loaders/WithoutLogin.tsx
  front/src/layout/Layout.tsx
  front/src/pages/LoginPage/index.tsx
  front/src/pages/NotFoundPage.tsx
  front/src/pages/ReservationPage/SectionAndSeat.tsx
  front/src/pages/ReservationPage/index.tsx
  front/src/pages/ReservationWaitingPage/index.tsx
  front/src/pages/SignupPage/index.tsx
Labels: 🔧프론트

#239 Guest모드 추가
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/entity/user.entity.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature

#241 예매 매수 변경 시 선점한 좌석들 반납
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/booking/service/in-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#242 관리자 기능: 이벤트 오픈 스케줄 리프레시
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, ✨feature
