Repository boostcampwm-2024/web04-RealTicket, pull requests merged in 2024-12, with the labels that each got.

#252 게스트 삭제 기능
  back/src/domains/user/controller/user.controller.ts
  back/src/domains/user/repository/user.repository.ts
  back/src/domains/user/service/user.service.ts
Labels: 🛠️백엔드, ✨feature

#253 관리자 기능: 오픈된 이벤트 상태 초기화
  back/src/domains/booking/controller/booking.controller.ts
  back/src/domains/booking/service/in-booking.service.ts
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#255 예매 내역 삭제 시 좌석 반납
  back/src/domains/booking/booking.module.ts
  back/src/domains/booking/service/booking.service.ts
  back/src/domains/reservation/repository/reservation.repository.ts
  back/src/domains/reservation/service/reservation.service.ts
Labels: 🛠️백엔드, ✨feature

#262 없어진 유저에 대한 상태 초기화 시 에러
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#267 예매 취소 시 잘못된 좌석 인덱스 설정으로 인해 안되는 에러
  back/src/domains/reservation/entity/reservedSeat.entity.ts
  back/src/domains/reservation/service/reservation.service.ts
Labels: 🛠️백엔드, 🚨hotfix

#270 SSE 연결에서 하트비트 메시지 송신
  back/src/domains/booking/const/sseMaximumInterval.ts
  back/src/domains/booking/service/booking-seats.service.ts
  back/src/domains/booking/service/waiting-queue.service.ts
Labels: 🛠️백엔드, ✨feature

#286 정기적 오픈 스케줄링 시 에러 캐치 및 로깅
  back/src/domains/booking/service/open-booking.service.ts
Labels: 🛠️백엔드, ✨feature

#293 대기 큐 입장 조건 판단 오류 수정
  front/src/pages/WaitingQueuePage/index.tsx
Labels: 🔧프론트, 🚨hotfix
